#! /bin/bash

export HOME=/root

typeset -A backups
backups=(
  [ffmapdata]=/opt/freifunk/meshviewer/data/
  [graphite]=/var/lib/graphite/
  [eventlogdb]=/opt/freifunk/meshviewer/ffv-nodes2eventlog/db
  [eventlogdb60]=/opt/freifunk/meshviewer/ffv-nodes2eventlog/db-threshold60
  [yanic]=/var/lib/yanic/
  [influxdb]=/var/lib/influxdb/
)

for backup in "${!backups[@]}"; do
(
  set -e

  export BORG_REPO=ssh://ffvbackup@office.simonwunderlich.de:23890/~/"${backup}"
  export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes

  borg create                       \
    --verbose                       \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
                                    \
    ::'{hostname}-{now}'            \
    "${backups[$backup]}"           \

  borg prune                        \
    --list                          \
    --prefix '{hostname}-'          \
    --show-rc                       \
    --keep-daily    7               \
    --keep-weekly   4               \
    --keep-monthly  6               \

)
done
