---
- name: remove rsyslog
  apt:
    pkg:
    - rsyslog
    state: absent
    purge: true

- name: add journald configuration folder
  file:
    path: "/etc/systemd/journald.conf.d/"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: drop invalid persistant file
  file:
    path: /etc/systemd/journald.conf.d/00_persistant.conf
    state: absent
  notify:
  - restart journald

- name: add journald persistent configuration
  copy:
    src: 00_persistent.conf
    dest: /etc/systemd/journald.conf.d/00_persistent.conf
  notify:
  - restart journald

# ensure that all services run with the correct config before continuing
- meta: flush_handlers
