# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: restart bb-ifupdown
  command: ifdown -a --allow=bb
  notify:
  - start bb-ifupdown

- name: start bb-ifupdown
  command: ifup -a --allow=bb
