# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: add apt https support
  apt:
    pkg:
    - apt-transport-https
    state: present

- name: enable grafana apt key
  apt_key:
    data: "{{ lookup('file', 'grafana.asc') }}"
    state: present 
    keyring: /etc/apt/trusted.gpg.d/grafana.gpg

- name: add grafana apt sources
  copy:
    src: grafana.list
    dest: /etc/apt/sources.list.d/grafana.list
  notify: update apt-cache

- name: add grafana apt preferences
  copy:
    src: grafana.pref
    dest: /etc/apt/preferences.d/grafana.pref
  notify: update apt-cache

- meta: flush_handlers

- name: install grafana dependencies
  apt:
    pkg:
    - apache2
    - grafana
    - libapache2-mod-wsgi
    - influxdb
    - sqlite3
    state: present

- name: enable apache rewrite
  apache2_module:
    state: present
    name: rewrite
  notify:
  - restart apache2

- name: add grafana dashboard provisioning configuration
  copy:
    src: ffv.yaml
    dest: /etc/grafana/provisioning/dashboards/ffv.yaml
    owner: root
    group: grafana
    mode: 0640
  notify: restart grafana-server

- name: add grafana configuration
  copy:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: 0640
  notify: restart grafana-server

- name: add influxdb config
  copy:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
  notify:
  - restart influxdb

- name: enable port 8080 for apache2
  lineinfile:
    destfile: '/etc/apache2/ports.conf'
    state: present
    regexp: '^Listen\s+8080$'
    line: 'Listen 8080'
  notify:
  - restart apache2

- name: enable apache2 http2
  apache2_module:
    name: http2
    state: present
  notify:
  - restart apache2

- name: enable apache2 mod_wsgi
  apache2_module:
    name: wsgi
    state: present
  notify:
  - restart apache2

- name: add apache2 stats site
  copy:
    src: apache2-stats.conf
    dest: /etc/apache2/sites-enabled/apache2-stats.conf
  notify:
  - restart apache2
