---
- name: restart networkd
  systemd:
    name: systemd-networkd.service
    state: "restarted"

- name: restart batadv-bat0
  systemd:
    name: batadv-bat0.service
    state: "restarted"

- name: restart vxlan0
  systemd:
    name: vxlan0.service
    state: "restarted"
