---
- name: restart networkd
  systemd:
    name: systemd-networkd.service
    state: "restarted"

- name: restart batadv-bat-{{ mesh_name }}
  systemd:
    name: batadv-bat-{{ mesh_name }}.service
    state: "restarted"

- name: restart vxlan-{{ mesh_name }}
  systemd:
    name: vxlan-{{ mesh_name }}.service
    state: "restarted"

- name: restart bridge-vpn
  systemd:
    name: "bridge-vpn@{{ mesh_name }}.service"
    state: restarted
