---
- name: install server-script dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - iproute2
  - batctl
  - procps

- name: Install server scripts
  git:
    repo: 'https://github.com/FreifunkVogtland/server-scripts.git'
    dest: /opt/freifunk/server-scripts

- name: add iproute freifunk alias
  lineinfile:
    destfile: '/etc/iproute2/rt_tables'
    state: present
    regexp: '^100\s'
    line: '100     freifunk'

- name: install server-scripts service
  copy:
    src: server-scripts.service
    dest: /etc/systemd/system/server-scripts.service

- name: enable server-scripts service
  systemd:
    name: server-scripts.service
    daemon_reload: yes
    enabled: yes
