# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: restart radvd
  systemd:
    name: radvd.service
    state: "{{ (USE_RADVD == '1') | ternary('restarted', 'stopped') }}"
