---
- name: install logrotate dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - logrotate

- name: install default logrotate config
  copy:
    src: rsyslog
    dest: /etc/logrotate.d/rsyslog
