# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: install logrotate dependencies
  apt:
    pkg:
    - logrotate
    state: present

- name: install default logrotate config
  copy:
    src: rsyslog
    dest: /etc/logrotate.d/rsyslog

# ensure that all services run with the correct config before continuing
- meta: flush_handlers
