---
- name: install alfred-json dependencies
  apt: pkg={{ item }} state=installed
  with_items:
  - build-essential
  - git
  - cmake
  - libjansson-dev
  - pkg-config
  - zlib1g-dev

- name: clone alfred-json
  git:
    repo: https://github.com/FreifunkVogtland/alfred-json.git
    dest: /usr/src/alfred-json
  register: clone_alfred_json

- name: create alfred-json build
  file: state=directory path=/usr/src/alfred-json/build

- stat: path=/usr/src/alfred-json/build/src/alfred-json
  register: build_alfred_json

- name: build alfred-json
  command: "{{ item }} chdir=/usr/src/alfred-json/build"
  with_items:
    - cmake ..
    - make
  when: clone_alfred_json.changed or (build_alfred_json.stat.exists == False)

- name: install alfred-json
  file:
    src: /usr/src/alfred-json/build/src/alfred-json
    dest: /usr/local/bin/alfred-json
    state: link
