---
- name: install bird dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - bird
  - iproute2

- name: install icvpn bird config stubs
  copy:
    content: ""
    dest: "/var/tmp/{{ item }}.conf"
    force: no
    group: root
    owner: root
    mode: 0644
  with_items:
  - bird-icvpn
  - bird6-icvpn
  - bird-icvpn-roa
  - bird6-icvpn-roa

- name: install bird config
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/bird/{{ item }}.conf"
    group: bird
    owner: bird
    mode: 0640
  notify:
  - "restart {{ item }}"
  with_items:
  - bird
  - bird6

- name: enable/disable bird
  systemd:
    name: "{{ item }}.service"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items:
  - bird
  - bird6

- name: install bb_ipv4 service
  template:
    src: bb_ipv4.service.j2
    dest: /etc/systemd/system/bb_ipv4.service
  notify:
  - restart bb_ipv4

- name: start bb_ipv4
  systemd:
    name: bb_ipv4.service
    daemon_reload: yes
    enabled: yes
    state: started
