# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: install vxlan-offloading dependencies
  apt:
    pkg:
    - iproute2
    state: present

- name: install mow-ffv_pl service
  template:
    src: mow-ffv_pl.service.j2
    dest: /etc/systemd/system/mow-ffv_pl.service
  notify:
  - restart mow-ffv_pl

- name: start mow-ffv_pl
  systemd:
    name: mow-ffv_pl.service
    daemon_reload: yes
    enabled: yes
    state: started
