# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: restart tinc
  systemd:
    name: tinc@icvpn.service
    state: "{{ icvpn | ternary('restarted', 'stopped') }}"
