---
- name: load nf_conntrack for tunneldigger
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - l2tp_core
  - l2tp_eth
  - l2tp_netlink
  - nf_conntrack_netlink
  - nf_conntrack
  - nfnetlink
  
- name: load modules for tunneldigger during boot
  lineinfile:
    dest: /etc/modules
    line: "{{ item }}"
  with_items:
  - l2tp_core
  - l2tp_eth
  - l2tp_netlink
  - nf_conntrack_netlink
  - nf_conntrack
  - nfnetlink

- name: drop legacy module from boot
  lineinfile:
    dest: /etc/modules
    line: "{{ item }}"
    state: absent
  with_items:
  - nf_conntrack_ipv4

- name: install tunneldigger dependencies
  apt:
    pkg:
    - iproute2
    - batctl
    - bridge-utils
    - conntrack
    - libnetfilter-conntrack3
    - python-dev
    - libevent-dev
    - python-virtualenv
    - libnfnetlink-dev
    - libnetfilter-conntrack-dev
    state: present

- name: install tunneldigger
  git:
    repo: 'https://github.com/FreifunkVogtland/tunneldigger.git'
    dest: /opt/freifunk/tunneldigger
    version: 05cdd3588952ef0623579dd3867f97f965b14917
  notify:
  - restart tunneldigger

- name: install tunneldigger requirements.txt
  copy:
    src: requirements.txt
    dest: "/opt/freifunk/tunneldigger/broker/requirements.txt"
    group: root
    owner: root
    mode: 0644

- name: install tunneldigger pip dependencies
  pip:
    requirements: /opt/freifunk/tunneldigger/broker/requirements.txt
    virtualenv: /opt/freifunk/tunneldigger
  notify:
  - restart tunneldigger

- name: setup tunneldigger
  shell: /opt/freifunk/tunneldigger/bin/python /opt/freifunk/tunneldigger/broker/setup.py install
  args:
    chdir: /opt/freifunk/tunneldigger/broker/

- name: create tunneldigger scripts directory
  file:
    dest: /opt/freifunk/tunneldigger/scripts/
    state: directory

- name: install tunneldigger hook scripts
  copy:
    src: "{{ item }}"
    dest: "/opt/freifunk/tunneldigger/scripts/{{ item }}"
    group: root
    owner: root
    mode: 0755
  with_items:
  - session-pre-down.sh
  notify:
  - restart tunneldigger

- name: generate tunneldigger hook scripts
  template:
    src: "{{ item }}.j2"
    dest: "/opt/freifunk/tunneldigger/scripts/{{ item }}"
    group: root
    owner: root
    mode: 0755
  with_items:
  - session-up.sh
  notify:
  - restart tunneldigger

- name: install broker startup script
  copy:
    src: start-broker.sh
    dest: /opt/freifunk/tunneldigger/start-broker.sh
    group: root
    owner: root
    mode: 0755
  notify:
  - restart tunneldigger

- name: create broker configuration
  template:
    src: l2tp_broker.cfg.j2
    dest: /opt/freifunk/tunneldigger/broker/l2tp_broker.cfg
  notify:
  - restart tunneldigger

- name: install tunneldigger service
  template:
    src: tunneldigger.service.j2
    dest: /etc/systemd/system/tunneldigger.service
  notify:
  - restart tunneldigger

- name: start tunneldigger
  systemd:
    name: tunneldigger.service
    daemon_reload: yes
    enabled: yes
    state: started
