---
gateway_if: eth0
batadv_version: 2018.1-10-gd36739f0
meshviewer: 0
icvpn: no

WANIP: "127.0.0.2"
WANGW: ""
WANGW6: "::1"
OWNASN: "64857"
BACKBONE_IPV4: ""
USE_RADVD: "0"
DIRECT: "0"

ffrl_bb_asn: 201701
ffrl_bb_links: {}
ffrl_bb_servers:
  bb_a_ak_ber: 185.66.195.0
  bb_a_fra2_fra: 185.66.194.0
  bb_a_ix_dus: 185.66.193.0
  bb_b_ak_ber: 185.66.195.1
  bb_b_fra2_fra: 185.66.194.1
  bb_b_ix_dus: 185.66.193.1
