# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
gateway_if: eth0
meshviewer: 0
icvpn: no
https: yes

vogtland_ipv4 : 10.204.0.0/16

WANGW: ""
WANGW6: "::1"
OWNASN: "64857"
USE_RADVD: "0"
DIRECT: "0"

fastd_enable: yes
fastd_peer_limit: -1
fastd_client_cost: 1

vxlan_enable: yes
bird_enable: yes

bgp_vxlanid: 15066820
bgp_ipv4: "{{ '169.254.0.0/16' | ipaddr(vpnid|int) }}"
bgp_ipv6: "{{ 'fd00::/8' | ipsubnet(16, 1) | ipaddr(vpnid|int) }}"

ffrl_ipv6_subnet: 2a03:2260:200f::/48

BGPID: "{{ WANIP }}"
ROUTERID: "{{ vogtland_ipv4 | ipaddr(vpnid|int - 1 + 2) | ipaddr('address') }}"
ROUTERRANGEV6: "{{ ffrl_ipv6_subnet|ipsubnet(56, vpnid|int) }}"

# FFV legacy 2a03:2260:200f:1337:: ranges
OLDRANGEV6: "{{ ffrl_ipv6_subnet|ipsubnet(56, 19) }}"
ROUTERIDV6: "{{ OLDRANGEV6|ipsubnet(64, 55) | ipaddr(vpnid|int) }}"

firmware_server: ""

mesh_meta:
  ffv:
    id: 0
    vxlan:
      id: 4184373
    ipv4:
      subnet: "{{ vogtland_ipv4 | ipsubnet(19, 0) }}"
      vpn_start: 2
      client_start: 12
      per_vpn: 818
    ipv6:
      prefix_64: 0
  pl:
    id: 1
    vxlan:
      id: 3699144
    ipv4:
      subnet: "{{ vogtland_ipv4 | ipsubnet(20, 2) }}"
      vpn_start: 2
      client_start: 12
      per_vpn: 408
    ipv6:
      prefix_64: 1
  tr:
    id: 2
    vxlan:
      id: 13947320
    ipv4:
      subnet: "{{ vogtland_ipv4 | ipsubnet(20, 3) }}"
      vpn_start: 2
      client_start: 12
      per_vpn: 408
    ipv6:
      prefix_64: 2
  rc:
    id: 3
    vxlan:
      id: 11488563
    ipv4:
      subnet: "{{ vogtland_ipv4 | ipsubnet(20, 4) }}"
      vpn_start: 2
      client_start: 12
      per_vpn: 408
    ipv6:
      prefix_64: 3
  s:
    id: 4
    vxlan:
      id: 2329586
    ipv4:
      subnet: "{{ vogtland_ipv4 | ipsubnet(20, 5) }}"
      vpn_start: 2
      client_start: 12
      per_vpn: 408
    ipv6:
      prefix_64: 4
  oel:
    id: 5
    vxlan:
      id: 2802234
    ipv4:
      subnet: "{{ vogtland_ipv4 | ipsubnet(20, 6) }}"
      vpn_start: 2
      client_start: 12
      per_vpn: 408
    ipv6:
      prefix_64: 5
  poe:
    id: 6
    vxlan:
      id: 8104281
    ipv4:
      subnet: "{{ vogtland_ipv4 | ipsubnet(20, 7) }}"
      vpn_start: 2
      client_start: 12
      per_vpn: 408
    ipv6:
      prefix_64: 6
  mtl:
    id: 7
    vxlan:
      id: 3708219
    ipv4:
      subnet: "{{ vogtland_ipv4 | ipsubnet(20, 8) }}"
      vpn_start: 2
      client_start: 12
      per_vpn: 408
    ipv6:
      prefix_64: 7

mesh: "{{ mesh_meta | mesh_fill(vpnid|int, ROUTERRANGEV6) }}"

fastd_mac_prefix: "{{ '02:fa:57:%02x:00'|format(vpnid|int) }}"

ffrl_bb_asn: 201701
ffrl_bb_links: {}
ffrl_bb_servers:
  bb_a_ak_ber: 185.66.195.0
  bb_a_fra2_fra: 185.66.194.0
  bb_a_ix_dus: 185.66.193.0
  bb_b_ak_ber: 185.66.195.1
  bb_b_fra2_fra: 185.66.194.1
  bb_b_ix_dus: 185.66.193.1

ffv_domains:
  ffv:
    id: 0
    mesh: ffv
  ffv_a:
    id: 1
    mesh: ffv
  ffv_ae:
    id: 2
    mesh: ffv
  ffv_b:
    id: 3
    mesh: ffv
  ffv_bb:
    id: 4
    mesh: ffv
  ffv_be:
    id: 5
    mesh: ffv
  ffv_boe:
    id: 6
    mesh: ffv
  ffv_eic:
    id: 7
    mesh: ffv
  ffv_ell:
    id: 8
    mesh: ffv
  ffv_els:
    id: 9
    mesh: ffv
  ffv_fst:
    id: 10
    mesh: ffv
  ffv_gb:
    id: 11
    mesh: ffv
  ffv_hdg:
    id: 12
    mesh: ffv
  ffv_k:
    id: 13
    mesh: ffv
  ffv_l:
    id: 14
    mesh: ffv
  ffv_le:
    id: 15
    mesh: ffv
  ffv_mh:
    id: 16
    mesh: ffv
  ffv_mkn:
    id: 17
    mesh: ffv
  ffv_mtl:
    id: 18
    mesh: mtl
  ffv_n:
    id: 19
    mesh: ffv
  ffv_nmk:
    id: 20
    mesh: ffv
  ffv_nst:
    id: 21
    mesh: ffv
  ffv_nsz:
    id: 22
    mesh: ffv
  ffv_oel:
    id: 23
    mesh: oel
  ffv_pl:
    id: 24
    mesh: pl
  ffv_pmf:
    id: 25
    mesh: ffv
  ffv_poe:
    id: 26
    mesh: poe
  ffv_rbh:
    id: 27
    mesh: ffv
  ffv_rc:
    id: 28
    mesh: rc
  ffv_rdw:
    id: 29
    mesh: ffv
  ffv_s:
    id: 30
    mesh: s
  ffv_sbg:
    id: 31
    mesh: ffv
  ffv_t:
    id: 32
    mesh: ffv
  ffv_tdf:
    id: 33
    mesh: ffv
  ffv_tr:
    id: 34
    mesh: tr
  ffv_tri:
    id: 35
    mesh: ffv
  ffv_wei:
    id: 36
    mesh: ffv
  ffv_wer:
    id: 37
    mesh: ffv
  fferz:
    id: 38
    mesh: ffv
