---
gateway_if: eth0
batadv_version: 2017.0.1-7-gdcc08cd
meshviewer: 0
icvpn: no

WANIP: "127.0.0.2"
WANGW: ""
WANGW6: "::1"
OWNASN: "64857"
BACKBONE_IPV4: ""
BACKBONE_IPV6: ""
USE_RADVD: "0"
SHAPE_LIMIT: ""
DIRECT: "0"
