# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: install ssh server
  apt:
    pkg:
    - openssh-server
    state: present

- name: install local ssh config
  copy:
    src: local.conf
    dest: /etc/ssh/sshd_config.d/local.conf
    owner: root
    group: root
    mode: 0644
  notify: restart sshd

# ensure that all services run with the correct config before continuing
- meta: flush_handlers
