---
- name: install ssh server
  apt: pkg={{ item }} state=present
  with_items:
  - openssh-server

- name: disable root ssh password login
  lineinfile:
    destfile: '/etc/ssh/sshd_config'
    state: present
    regexp: '^#?PermitRootLogin\s'
    line: 'PermitRootLogin prohibit-password'
  notify: restart sshd

- name: disable ssh password login
  lineinfile:
    destfile: '/etc/ssh/sshd_config'
    state: present
    regexp: '^#?PasswordAuthentication\s'
    line: 'PasswordAuthentication no'
  notify: restart sshd

- name: insert/update ssh sftponly/borgonly chroot
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      Match Group sftponly
        ChrootDirectory %h
        ForceCommand internal-sftp
        AllowTcpForwarding no
        X11Forwarding no
        PasswordAuthentication no
        PermitTunnel no
      
      Match Group borgonly
        ForceCommand borg serve --restrict-to-path $HOME
        AllowTcpForwarding no
        X11Forwarding no
        PasswordAuthentication no
        PermitTunnel no
  notify: restart sshd
