---
- name: install fastd dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - iproute2
  - batctl
  - fastd

- name: create fastd instance directories
  file:
    state: directory
    path: /etc/fastd/{{ item }}/
  with_items: "{{ ffv_domains }}"

- name: install fastd config
  template:
    src: fastd.conf.j2
    dest: /etc/fastd/{{ item }}/fastd.conf
  with_items: "{{ ffv_domains }}"
  notify:
  - restart fastd

- name: disable sysv initscript
  systemd:
    name: fastd.service
    daemon_reload: yes
    enabled: no
    state: stopped

- name: create batadv-bat-X override directory
  file:
    dest: /etc/systemd/system/fastd@.service.d
    state: directory

- name: enabled batadv-bat-X dependency for fastd
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/fastd@.service.d/override.conf
  notify:
  - restart fastd

- name: start fastd
  systemd:
    name: "fastd@{{ item }}.service"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items: "{{ ffv_domains }}"
