---
- name: install firewall dependencies
  apt:
    pkg:
    - nftables
    state: present

- name: install nftables rules
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: 0755
  notify:
  - restart nftables

- name: enable nftables
  systemd:
    name: nftables.service
    daemon_reload: yes
    enabled: "yes"
    state: "started"
