#! /bin/sh
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>

letsencrypt renew > /dev/null 2>&1
chown :ssl-cert /etc/letsencrypt/archive /etc/letsencrypt/live
chmod g+x /etc/letsencrypt/archive /etc/letsencrypt/live
systemctl reload nginx > /dev/null
