---
- name: load nf_conntrack for sysctl settings
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - nf_conntrack
  - nf_conntrack_ipv4

- name: load nf_conntrack for sysctl settings on boot
  lineinfile:
    dest: /etc/modules
    line: "{{ item }}"
  with_items:
  - nf_conntrack
  - nf_conntrack_ipv4

- name: switch to fq_codel default qdisc
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/local.conf
  with_dict:
    net.core.default_qdisc: fq_codel

- name: enable tcp ecn
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/local.conf
  with_dict:
    net.ipv4.tcp_ecn: 1

- name: disable rp_filter
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/local.conf
  with_dict:
    net.ipv4.conf.default.rp_filter: 0
    net.ipv4.conf.all.rp_filter: 0

- name: enable forwarding
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/local.conf
  with_dict:
    net.ipv4.ip_forward: 1
    net.ipv6.conf.all.forwarding: 1
    net.ipv6.conf.default.forwarding: 1

- name: set neighbor gc_threshold
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/local.conf
  with_dict:
    net.ipv4.neigh.default.gc_thresh1: 32766
    net.ipv4.neigh.default.gc_thresh2: 32766
    net.ipv4.neigh.default.gc_thresh3: 32766

- name: set conntrack limits/timeouts
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/local.conf
  with_dict:
    net.nf_conntrack_max: 256000
    net.netfilter.nf_conntrack_generic_timeout: 120
    net.netfilter.nf_conntrack_tcp_timeout_established: 54000

- name: set printk ratelimit
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/local.conf
  with_dict:
    kernel.printk_ratelimit: 1
    kernel.printk_ratelimit_burst: 1000

- name: enable reboot on panic
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/local.conf
  with_dict:
    kernel.panic: 5
