---
- name: load modules for vpn bridge
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - ebtables
  - ebtable_filter

- name: load modules for vpn bridge during boot
  lineinfile:
    dest: /etc/modules
    line: "{{ item }}"
  with_items:
  - ebtables
  - ebtable_filter

- name: install batman-adv dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - bridge-utils
  - batctl
  - build-essential
  - ebtables
  - git
  - dkms
  - linux-headers-amd64
  - iproute2

- name: install batman-adv sources
  git:
    repo: 'https://github.com/FreifunkVogtland/batman-adv.git'
    dest: /usr/src/batman-adv-{{ batadv_version }}
    version: v{{ batadv_version }}

- name: install batadv dkms config
  template:
    src: dkms.conf.j2
    dest: /usr/src/batman-adv-{{ batadv_version }}/dkms.conf

- name: check for added batman-adv dkms
  stat:
    path: /var/lib/dkms/batman-adv/{{ batadv_version }}/source
  register: batadv_dkms_added

- name: register batman-adv dkms sources
  command: dkms add -m batman-adv -v {{ batadv_version }}
  when: batadv_dkms_added.stat.islnk is not defined

# TODO check whether it is already installed and not whether source link exists
- name: build batman-adv dkms sources
  command: dkms autoinstall -m batman-adv -v {{ batadv_version }}
  when: batadv_dkms_added.stat.islnk is not defined

- name: install dummy-bat0
  template:
    src: dummy-bat0.netdev.j2
    dest: /etc/systemd/network/25-dummy-bat0.netdev
  notify:
  - restart networkd

- name: install bat0 link
  template:
    src: bat0.link.j2
    dest: /etc/systemd/network/25-bat0.link
  notify:
  - restart networkd

- name: install bat0 network
  template:
    src: bat0.network.j2
    dest: /etc/systemd/network/25-bat0.network
  notify:
  - restart networkd

- meta: flush_handlers

- name: start systemd-networkd
  systemd:
    name: systemd-networkd.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: install batadv-bat0
  template:
    src: batadv-bat0.service.j2
    dest: /etc/systemd/system/batadv-bat0.service
  notify:
  - restart batadv-bat0

- name: start batadv-bat0
  systemd:
    name: batadv-bat0.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: install vxlan0 service
  template:
    src: vxlan0.service.j2
    dest: /etc/systemd/system/vxlan0.service
  notify:
  - restart vxlan0

- name: start vxlan0
  systemd:
    name: vxlan0.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: install vpn-ffv netdev
  template:
    src: vpn-ffv.netdev.j2
    dest: /etc/systemd/network/25-vpn-ffv.netdev
  notify:
  - restart networkd

- name: install vpn-ffv network
  copy:
    src: vpn-ffv.network
    dest: /etc/systemd/network/25-vpn-ffv.network
  notify:
  - restart networkd

- meta: flush_handlers

- name: start systemd-networkd
  systemd:
    name: systemd-networkd.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: install vpn-ffv bridge service
  copy:
    src: bridge-vpn@.service
    dest: /etc/systemd/system/bridge-vpn@.service
  notify:
  - restart bridge-vpn

- name: start vpn bridge
  systemd:
    name: bridge-vpn@ffv.service
    daemon_reload: yes
    enabled: yes
    state: started
