---
- name: load modules for vpn bridge
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - ebtables
  - ebtable_filter

- name: load modules for vpn bridge during boot
  lineinfile:
    dest: /etc/modules
    line: "{{ item }}"
  with_items:
  - ebtables
  - ebtable_filter

- name: install batman-adv dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - bridge-utils
  - batctl
  - build-essential
  - ebtables
  - git
  - dkms
  - linux-headers-amd64
  - iproute2

- name: install batman-adv sources
  git:
    repo: 'https://github.com/FreifunkVogtland/batman-adv.git'
    dest: /usr/src/batman-adv-{{ batadv_version }}
    version: v{{ batadv_version }}

- name: install batadv dkms config
  template:
    src: dkms.conf.j2
    dest: /usr/src/batman-adv-{{ batadv_version }}/dkms.conf

- name: check for added batman-adv dkms
  stat:
    path: /var/lib/dkms/batman-adv/{{ batadv_version }}/source
  register: batadv_dkms_added

- name: register batman-adv dkms sources
  command: dkms add -m batman-adv -v {{ batadv_version }}
  when: batadv_dkms_added.stat.islnk is not defined

# TODO check whether it is already installed and not whether source link exists
- name: build batman-adv dkms sources
  command: dkms autoinstall -m batman-adv -v {{ batadv_version }}
  when: batadv_dkms_added.stat.islnk is not defined

- name: install dummy-bat-{{ mesh_name }}
  template:
    src: dummy-bat.netdev.j2
    dest: /etc/systemd/network/25-dummy-bat-{{ mesh_name }}.netdev
  notify:
  - restart networkd

- name: install bat-{{ mesh_name }} link
  template:
    src: bat.link.j2
    dest: /etc/systemd/network/25-bat-{{ mesh_name }}.link
  notify:
  - restart networkd

- name: install bat-{{ mesh_name }} network
  template:
    src: bat.network.j2
    dest: /etc/systemd/network/25-bat-{{ mesh_name }}.network
  notify:
  - restart networkd

- meta: flush_handlers

- name: start systemd-networkd
  systemd:
    name: systemd-networkd.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: install batadv-bat-{{ mesh_name }}
  template:
    src: batadv-bat.service.j2
    dest: /etc/systemd/system/batadv-bat-{{ mesh_name }}.service
  notify:
  - restart batadv-bat-{{ mesh_name }}

- name: start batadv-bat-{{ mesh_name }}
  systemd:
    name: batadv-bat-{{ mesh_name }}.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: install vxlan-{{ mesh_name }} service
  template:
    src: vxlan.service.j2
    dest: /etc/systemd/system/vxlan-{{ mesh_name }}.service
  notify:
  - restart vxlan-{{ mesh_name }}

- name: start vxlan-{{ mesh_name }}
  systemd:
    name: vxlan-{{ mesh_name }}.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: install vpn-{{ mesh_name }} netdev
  template:
    src: vpn.netdev.j2
    dest: /etc/systemd/network/25-vpn-{{ mesh_name }}.netdev
  notify:
  - restart networkd

- name: install vpn-{{ mesh_name }} network
  template:
    src: vpn.network.j2
    dest: /etc/systemd/network/25-vpn-{{ mesh_name }}.network
  notify:
  - restart networkd

- meta: flush_handlers

- name: start systemd-networkd
  systemd:
    name: systemd-networkd.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: install vpn bridge service
  copy:
    src: bridge-vpn@.service
    dest: /etc/systemd/system/bridge-vpn@.service
  notify:
  - restart bridge-vpn

- name: start vpn-{{ mesh_name }} bridge
  systemd:
    name: bridge-vpn@{{ mesh_name }}.service
    daemon_reload: yes
    enabled: yes
    state: started
