# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: restart vxlan0
  systemd:
    name: vxlan0.service
    state: restarted

- name: restart bird
  systemd:
    name: bird.service
    state: restarted

- name: restart bb_ipv4
  systemd:
    name: bb_ipv4.service
    state: restarted

- name: restart ff_ip_policy
  systemd:
    name: ff_ip_policy.service
    state: restarted
