# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: install mapdata dependencies
  apt:
    pkg:
    - nginx-light
    - libnginx-mod-http-fancyindex
    state: present

- name: add nginx mapdata site
  template:
    src: mapdata.j2
    dest: /etc/nginx/sites-enabled/mapdata
  notify:
  - restart nginx

# ensure that all services run with the correct config before continuing
- meta: flush_handlers
