# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: install mapdata dependencies
  apt:
    pkg:
    - apache2
    state: present

- name: enable apache2 http2
  apache2_module:
    name: http2
    state: present
  notify:
  - restart apache2

- name: add apache2 mapdata site
  copy:
    src: apache2-mapdata.conf
    dest: /etc/apache2/sites-enabled/apache2-mapdata.conf
  notify:
  - restart apache2
