---
- name: install mapdata dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - apache2

- name: enable apache2 http2
  apache2_module:
    name: http2
    state: present
  notify:
  - restart apache2

- name: add apache2 mapdata site
  copy:
    src: apache2-mapdata.conf
    dest: /etc/apache2/sites-enabled/apache2-mapdata.conf
  notify:
  - restart apache2
