# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: install radvd
  apt:
    pkg:
    - radvd
    state: present

- name: install radvd configuration
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
  notify:
  - restart radvd

- name: enable/disable radvd
  systemd:
    name: radvd.service
    daemon_reload: yes
    enabled: "{{ (USE_RADVD == '1') | ternary('yes', 'no') }}"
    state: "{{ (USE_RADVD == '1') | ternary('started', 'stopped') }}"
