---
- name: install radvd
  apt: pkg={{ item }} state=present
  with_items:
  - radvd

- name: install radvd configuration
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
  notify:
  - restart radvd

- name: enable/disable radvd
  systemd:
    name: radvd.service
    daemon_reload: yes
    enabled: "{{ (USE_RADVD == '1') | ternary('yes', 'no') }}"
    state: "{{ (USE_RADVD == '1') | ternary('started', 'stopped') }}"
