---
# manual TODO
# certbot certonly --rsa-key-size 4096 \
# -a webroot --webroot-path /var/letsencrypt \
#     -d vpn05.freifunk-vogtland.net

- name: install server-statistics dependencies
  apt:
    pkg:
    - vnstati
    - php-fpm
    state: present

- name: drop libapache2-mod-php
  apt:
    pkg:
    - libapache2-mod-php7.0
    state: absent

- name: enable event mpm
  apache2_module:
    name: mpm_event
    state: present
  notify:
  - restart apache2

- name: enable apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
  - http2
  - headers
  - setenvif
  - proxy_fcgi
  - ssl
  notify:
  - restart apache2

- name: Activate configuration
  command:
    a2enconf php7.0-fpm.conf
    creates=/etc/apache2/conf-enabled/php7.0-fpm.conf
  notify: apache-reload

- name: add letsencrypt folder
  file:
    path: "/var/letsencrypt/"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: add letsencrypt .well-known folder
  file:
    path: "/var/letsencrypt/.well-known"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: add letsencrypt etc folder
  file:
    path: "/etc/letsencrypt/"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: add letsencrypt cron
  copy:
    src: cron-letsencrypt
    dest: /etc/cron.weekly/letsencrypt
    owner: root
    group: root
    mode: 0755

- name: add letsencrypt http ssl default options
  copy:
    src: options-ssl.conf
    dest: /etc/letsencrypt/options-ssl.conf
  notify: restart apache2

- name: add letsencrypt well-known
  copy:
    src: letsencrypt.conf
    dest: /etc/apache2/conf-enabled/letsencrypt.conf
  notify: restart apache2

- name: Install server statistics
  git:
    repo: 'https://github.com/FreifunkVogtland/ffc-server-statistics.git'
    dest: /var/www/vnstat

- name: remove old webserver index
  file:
    path: /var/www/html/index.html
    state: absent

- name: install server statistics index
  file:
    src: /var/www/vnstat/index.php
    dest: /var/www/html/index.php
    state: link

- name: install server statistics config
  template:
    src: stats.conf.j2
    dest: /var/www/vnstat/stats.conf

- name: install server statistics index
  file:
    src: /var/www/vnstat/stats.conf
    dest: /var/www/html/stats.conf
    state: link

- name: install server-statistics systemd unit file
  copy:
    src: server-statistics.service
    dest: /etc/systemd/system/server-statistics.service

- name: install server-statistics systemd timer file
  copy:
    src: server-statistics.timer
    dest: /etc/systemd/system/server-statistics.timer

- name: start server-statistics
  systemd:
    name: server-statistics.timer
    state: started
    daemon_reload: yes
    enabled: yes
