---
- name: add backports apt sources
  copy:
    src: etc/apt/sources.list.d/backports.list
    dest: /etc/apt/sources.list.d/backports.list
  notify: update apt-cache

- name: add backports apt preferences
  copy:
    src: etc/apt/preferences.d/backports.pref
    dest: /etc/apt/preferences.d/backports.pref
  notify: update apt-cache

- meta: flush_handlers

- name: install common packages
  apt: pkg={{ item }} state=present
  with_items:
  - etckeeper
  - screen
  - htop
  - bmon
  - mtr
  - iotop
  - vim
  - apticron
  - netcat
  - ntp
