---
- name: Install sudo
  apt: pkg={{ item }} state=installed
  with_items:
  - sudo

- name: Install passwordless sudo
  copy: src=etc/sudoers.d/sudo dest=/etc/sudoers.d/sudo

- apt: pkg=zsh state=installed
- name: Add user ecsv
  user:
    name: ecsv
    comment: "Sven Eckelmann"
    groups: sudo
    shell: /bin/zsh
    state: present

- name: Add SSH key user ecsv
  authorized_key:
    user: ecsv
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDpGUoxC8J6gXoNjOzNhVB6KhtNZ0QUSEnuxErVzkjoXlioYSeazNQnGFyBbUXQLk0B0+HZH83QvTubIzZqRVCq9GHmIJnUvlp0KyPmjcLttcfe798O1yrw6PqB38sWvQqDqe4Hicy/OavqDlwP1nOUDXOuFGWu4LQS9Gbhz9BDI1ihJ567TRmrPdWdVZ9UJrGWcMRvhSH2Ql91trOuKzb9p3/ZL75GdgQl0Sy/80LA/FZVBFkL90sCHQrz4DVeBNcCA+6OL9TcJmjGWUB7Ve9M32E/GFJ2DzNI8kwTzcXmnRPASaGXxV9RYDQIB2S2SMWtVcM1bgOhVdfsI6lsVJ+fG7iE/CKO18yPbf80CgUS11noRbm9kwuXPjC1OAkPCm4JHje11s51KfsJWlxBCRwlct3BU6O5L8VhGd77js2W8YCGDG/FchYBKpeLfRGQC1Q33jBF7xnrJvEkj39tpX7rt6TiXjM2IzzzVcJhrRkiqegFyRSJoFQbXGypPDXUyP0M0c+DEV51fa4zf0y+MohZCQrBdSIhuiWqYdqZMCsrp0zv+iHtQkBsY9+4s6e5+GjHu0dDY0qt7VR0KPLcWWepC5loNbz/3duLDV+gbc3QpMzFXyRodsl31HJxEjv8XP4TqetT+Z+Tz6xj4Qw/WSllPjDEzactf5IRWml9ddpk6w== Sven Eckelmann <sven@narfation.org>"

- name: Add user siwu
  user:
    name: siwu
    comment: "Simon Wunderlich"
    groups: sudo
    shell: /bin/bash
    state: present

- name: Add SSH key user siwu
  authorized_key:
    user: siwu
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC4vACkUU+q0xDsIS0DKIDWCTq960ruf4YOMCG2P3wQqo1gBmFutQPpHlT9dD57zTlhOBDQxu3vks//yJSjXQpdnbx6Wi3kuKkGWXJhA/lspA50jE6h8Cr0/s/q2imtC0/HZnoJcl9w+7jh71ghdVvn0ZKMBbe2nF3b0npjK1N32ZhzW3ryn+EJsPiUax0cIFxMAUQ3AAh9bo59NTSGH/pUNQBvkMs49MM9g0q59szhY72LfTqSGqyMsaoC4yjA5u2J258OF51epoz7pjpxE5uiUfR85gEPtQMsBLXD/2ejCrvj/ltQu8HT9e/rMY4p85YHlir9XsJYija26yb8Bq5tgdro48rX9Jyj0sxqPncs2wvv2rbN8iFcbW3vXDxKK/shVNCrpPX+KC6QouOpgXUrPBoEK3kfDspMY99Cm5brnlHskv2xznx/h/I8k9yQwRA6FEb8EpjIXQeOYAA04euONYaLNMxOFcL95CZHex3JqJQFdTL+895vZvlH3aPhBlSlyEgROQtSPVQPzDFRra1IDujxBAqPlbOXtW09XnNp3bLhu4aVsniplze4BRMfkiyPjXcsdBxL9G4smvaVjLXZ/MkSyn7UA6pYxAefV30ycC565EhagxzTz6mWHKVt3+U+XnR++RqEIkONw3ShnSSc0Aegx6RLgyr/APGTaLqFKw== Simon Wunderlich <sw@simonwunderlich.de>"

- name: Add user altima
  user:
    name: altima
    comment: "Enrico Meinel"
    groups: sudo
    shell: /bin/bash
    state: present

- name: Add SSH key user altima
  authorized_key:
    user: altima
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFu/h90kPZ2siR+OEQi7g78fjA9Yv6+F5rSXJIA8hEU+o+3LNTyjttj1RmrYdD7HRogPOXJdKc7hLwGIHr+2rToq80qD2s8nNerdgSVO2Kq4lB2t6+RDGv7UZAfBqles1YeSbLZGg+P/IDxFKMD3m9DEMhbHQNaZwyXgLTFZPGnq/gwPFVlEH2JTIEBctmJVLsDT+NFViEe4UbwMxvCDr34b8UmOUWkERbmJu4cbi9JFn9lLu1wc7N0/VPeZ9uYD1Z4KPV9xolO+EBdp4M1IagX1hcYVskXXtFKxqsLRNhJnFK8m+LCka2T13+If85/f7NH7kPZZjG9BNcNdpy4N0H3uAPh6Tr+68WbCDH4smxQ51GI1UIATnpGo+qbE3HkuBADyvTWhKGE4LAEhEteV0RO4kX2yD7JbFrTm7AUJpkIcbExVEiFnNTGYE+grCd2hli3tYtNO9LRla4HGNlVGxFY2Osi2MlgJacMteafPEM96tzBCDlN6s0rwlwQLn9ywa6m2iaTeOalfu5NgBjhwPY5MTXOhssFp+ybVNxwpFDtnF3lPJGH1K17BwhSxK1KTDf7SP+TfjjzchCj5nrR8DBqgm2kWgdiRoSIfMMuldnPy94cBmmN6QBcP2ldbB9f/8V6fkgNpdyQIIckaYEwKIQ1SijgtAm7BbpjSVO3WHAuQ== altima@work"

- name: Add group sftponly
  group:
    name: sftponly
    state: present

- name: Add user sftpbackup
  user:
    name: sftpbackup
    groups: sftponly
    shell: /bin/false
    state: present

- name: Add SSH key user sftpbackup
  authorized_key:
    user: sftpbackup
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnFrxKK3sYN57CvLJpaWkp8WfoikHPHYKLCLYlSNnHgFe8WsSZ+PBzoxWZsGPJYvVDEK7kcVp5odPCBqGSdMABD3EpZbDbPgWuHOBOLUt2RUbGA9tb8x/oSLYnmIz5EowDHg+eYXAl0ZagL5fzhBsIKANHsl+DCd4A+FuaIUVMuCtWsC+1moLCSCsAOp6TTrBLmnwz3U9CxHs6+R/WGssgVupgLjaOghbhIUKFRvQQQYtURRhrFplNuEwcmEqicUQwofM6bQLPEGQIfPVXJBjNxDq6F9aPLMTWTxbFDzhs2mm+G/GlLSJuuRi+HflQFC21ygvluxKd/HsOW+Fz8NNZ root@vpn01"

- name: convert to chrootable sftpbackup
  file:
    state: directory
    path: /home/sftpbackup
    group: root
    owner: root
    mode: 0755

- name: create chrootable sftpbackup home
  file:
    state: directory
    path: /home/sftpbackup/home/sftpbackup
    group: sftpbackup
    owner: sftpbackup
    mode: 0755
