# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: update apt-cache
  apt: update_cache=true

- name: restart grafana-server
  systemd:
    name: grafana-server.service
    state: restarted

- name: restart nginx
  systemd:
    name: nginx.service
    state: restarted

- name: restart influxdb
  systemd:
    name: influxdb.service
    state: restarted
