---
- name: update apt-cache
  apt: update_cache=true

- name: restart grafana-server
  systemd:
    name: grafana-server.service
    state: restarted

- name: restart carbon-cache
  systemd:
    name: carbon-cache.service
    state: restarted

- name: restart apache2
  systemd:
    name: apache2.service
    state: restarted
