---
- name: install dnsmasq dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - dnsmasq

- name: Install dns-static
  git:
    repo: 'https://github.com/FreifunkVogtland/dns-static.git'
    dest: /opt/freifunk/dns

- name: install dns-static ether
  file:
    src: /opt/freifunk/dns/ethers
    dest: /etc/ethers
    state: link

- name: install icvpn dnsmasq config stub
  copy:
    content: ""
    dest: /var/tmp/dnsmasq-icvpn.conf
    force: no
    group: root
    owner: root
    mode: 0644

- name: install dnsmasq config
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify:
  - restart dnsmasq
  when: dnsmasq

- name: enable/disable dnsmasq
  systemd:
    name: dnsmasq.service
    daemon_reload: yes
    enabled: "{{ dnsmasq | ternary('yes', 'no') }}"
    state: "{{ dnsmasq | ternary('started', 'stopped') }}"

- name: create dnsmasq-cron script directory
  file:
    path: /opt/freifunk/server-scripts/
    state: directory
    owner: root

- name: install dnsmasq-cron scripts
  copy:
    src: dnsmasq-cron.sh
    dest: /opt/freifunk/server-scripts/dnsmasq-cron.sh
    group: root
    owner: root
    mode: 0755

- name: install dnsmasq-cron systemd unit file
  copy:
    src: dnsmasq-cron.service
    dest: /etc/systemd/system/dnsmasq-cron.service

- name: install dnsmasq-cron systemd timer file
  copy:
    src: dnsmasq-cron.timer
    dest: /etc/systemd/system/dnsmasq-cron.timer

- name: start dnsmasq-cron timer
  systemd:
    name: dnsmasq-cron.timer
    state: started
    daemon_reload: yes
    enabled: yes
