---
gateway_if: eth0
meshviewer: 0
icvpn: yes
dnsmasq: yes
vpnid: 4

WANIP: "88.99.151.81"
WANGW: "88.99.151.65"
WANIP6: "2a01:4f8:10a:2f8f::2"
WANGW6: "::1"
ROUTERID: "{{ '10.204.%d.1'|format(vpnid * 16|int) }}"
ROUTERIDV6: "{{ '2a03:2260:200f:1337::%x'|format(vpnid|int) }}"
ROUTERIPV6: "{{ '2a03:2260:200f:%x00::1'|format(vpnid|int) }}"
ROUTERRANGEV6: "{{ '2a03:2260:200f:%x00::'|format(vpnid|int) }}"
DNSMASQ_RANGE: "{{ '10.204.%d.0,10.204.%d.255'|format(vpnid * 16|int, vpnid * 16 + 15|int) }}"
BACKBONE_IPV4: "185.66.194.70/32"
USE_RADVD: "1"
DIRECT: "0"

batadv_mac: "{{ '02:ba:7a:df:%02x:00'|format(vpnid|int) }}"
batadv_primary: "{{ '02:62:e7:ab:%02x:%02x'|format(vpnid|int, vpnid|int) }}"

icvpn_name: vogtland4
icvpn_ipv4: 10.207.0.93
icvpn_bcast: 10.207.255
icvpn_ipv6: fec0::a:cf:0:5d

fastd_peer_limit: 30
fastd_mac_prefix: "{{ '02:fa:57:%02x:00'|format(vpnid|int) }}"

tunneldigger_peer_limit: 120

ffrl_bb_links:
  bb_a_ak_ber:
    ipv4:
      src: 100.64.9.31
      dst: 100.64.9.30
    ipv6:
      src: 2a03:2260:0:4a4::2
      dst: 2a03:2260:0:4a4::1
  bb_a_fra2_fra:
    ipv4:
      src: 100.64.9.33
      dst: 100.64.9.32
    ipv6:
      src: 2a03:2260:0:4a5::2
      dst: 2a03:2260:0:4a5::1
  bb_a_ix_dus:
    ipv4:
      src: 100.64.9.35
      dst: 100.64.9.34
    ipv6:
      src: 2a03:2260:0:4a6::2
      dst: 2a03:2260:0:4a6::1
  bb_b_ak_ber:
    ipv4:
      src: 100.64.9.37
      dst: 100.64.9.36
    ipv6:
      src: 2a03:2260:0:4a7::2
      dst: 2a03:2260:0:4a7::1
  bb_b_fra2_fra:
    ipv4:
      src: 100.64.9.39
      dst: 100.64.9.38
    ipv6:
      src: 2a03:2260:0:4a8::2
      dst: 2a03:2260:0:4a8::1
  bb_b_ix_dus:
    ipv4:
      src: 100.64.9.41
      dst: 100.64.9.40
    ipv6:
      src: 2a03:2260:0:4a9::2
      dst: 2a03:2260:0:4a9::1
