---
- name: install backup dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - anacron
  - cron
  - borgbackup

- name: copy backup.daily cron script
  copy:
    src: backup.daily
    dest: /etc/cron.daily/backup
    mode: 0755

- name: copy backup.hourly cron script
  copy:
    src: backup.hourly
    dest: /etc/cron.hourly/backup
    mode: 0755
