# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: install backup dependencies
  apt:
    pkg:
    - anacron
    - cron
    - borgbackup
    state: present

- name: copy backup.daily cron script
  copy:
    src: backup.daily
    dest: /etc/cron.daily/backup
    mode: 0755

- name: copy backup.hourly cron script
  copy:
    src: backup.hourly
    dest: /etc/cron.hourly/backup
    mode: 0755
