---
- name: install backup dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - anacron
  - cron
  - borgbackup

- name: copy backup cron script
  copy:
    src: backup
    dest: /etc/cron.daily/backup
    mode: 0755
