---
gateway_if: ens192
meshviewer: 0
icvpn: yes
dnsmasq: yes
vpnid: 6

WANIP: "178.63.227.200"
WANGW: "178.63.227.192"
WANIP6: "2a01:4f8:110:6ffe::6666"
WANGW6: "2a01:4f8:110:6ffe::1"
USE_RADVD: "0"
SHAPE_LIMIT: ""
DIRECT: "0"

icvpn_name: vogtland6
icvpn_ipv4: 10.207.0.7
icvpn_bcast: 10.207.255
icvpn_ipv6: fec0::a:cf:0:7

fastd_peer_limit: 30

tunneldigger_peer_limit: 120
