# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: install bind dependencies
  apt:
    pkg:
    - bind9
    state: present

- name: remove bind conflicting packages
  apt:
    pkg:
    - apparmor
    state: absent

- name: install bind named.conf.options
  copy:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
    group: bind
    owner: root
    mode: 0644
  notify:
  - restart bind

- name: install icvpn bind config stub
  copy:
    content: ""
    dest: /var/tmp/bind-icvpn.conf
    force: no
    group: root
    owner: root
    mode: 0644

- name: install bind named.conf.local
  copy:
    src: named.conf.local
    dest: /etc/bind/named.conf.local
    group: bind
    owner: root
    mode: 0644
  notify:
  - restart bind

- name: install icvpn dnsmasq config stub
  copy:
    content: ""
    dest: /var/tmp/dnsmasq-icvpn.conf
    force: no
    group: root
    owner: root
    mode: 0644

- name: enable bind
  systemd:
    name: bind9.service
    daemon_reload: yes
    enabled: "yes"
    state: "started"

# ensure that all services run with the correct config before continuing
- meta: flush_handlers
