---
gateway_if: eth0
meshviewer: 0
icvpn: yes
dnsmasq: yes
vpnid: 5

WANIP: "185.185.26.86"
WANGW: "185.185.26.1"
WANIP6: "2a01:4f8:bc:ae6::7286"
WANGW6: "::1"
USE_RADVD: "0"
DIRECT: "0"

icvpn_name: vogtland5
icvpn_ipv4: 10.207.0.4
icvpn_bcast: 10.207.255
icvpn_ipv6: fec0::a:cf:0:4

fastd_peer_limit: 30

tunneldigger_peer_limit: 120
