# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: restart fastd
  systemd:
    name: "fastd@{{ item }}.service"
    state: "{{ fastd_enable | ternary('restarted', 'stopped') }}"
  with_items: "{{ ffv_domains.keys() }}"

- name: restart fastd_slow_balancer
  systemd:
    name: "fastd_slow_balancer.service"
    state: "{{ fastd_enable | ternary('restarted', 'stopped') }}"

- name: reload fastd peers
  shell: killall -SIGHUP fastd || true
