---
- name: install mesh-announce dependencies
  apt: pkg={{ item }} state=installed
  with_items:
  - lsb-release
  - ethtool
  - python3
  - batctl

- name: install mesh-announce
  git:
    repo: 'https://github.com/FreifunkVogtland/mesh-announce'
    dest: /opt/freifunk/ffnord-alfred-announce

- name: install respondd systemd unit file
  copy:
    src: respondd.service
    dest: /etc/systemd/system/respondd.service
  notify:
  - restart respondd

- name: start respondd
  systemd:
    name: respondd.service
    state: started
    daemon_reload: yes
    enabled: yes
