# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2017-2020, Sven Eckelmann <sven@narfation.org>
---
- name: install mesh-announce dependencies
  apt:
    pkg:
    - lsb-release
    - ethtool
    - python3
    - batctl
    state: present

- name: install mesh-announce
  git:
    repo: 'https://github.com/FreifunkVogtland/mesh-announce'
    dest: /opt/freifunk/ffnord-alfred-announce
    version: 9e357956064fcee4925af2b6099e431eb5460279
  notify:
  - restart respondd

- name: install respondd systemd unit file
  template:
    src: respondd.service.j2
    dest: /etc/systemd/system/respondd.service
  notify:
  - restart respondd

- name: start respondd
  systemd:
    name: respondd.service
    state: "{{ vxlan_enable | ternary('started', 'stopped') }}"
    daemon_reload: yes
    enabled: "{{ vxlan_enable | ternary('yes', 'no') }}"

# ensure that all services run with the correct config before continuing
- meta: flush_handlers
