---
- name: install mesh-announce dependencies
  apt:
    pkg:
    - lsb-release
    - ethtool
    - python3
    - batctl
    state: present

- name: install mesh-announce
  git:
    repo: 'https://github.com/FreifunkVogtland/mesh-announce'
    dest: /opt/freifunk/ffnord-alfred-announce
    version: 5fe8f33514dbcf3e6efca5de060407d99283a8a2

- name: install respondd systemd unit file
  template:
    src: respondd.service.j2
    dest: /etc/systemd/system/respondd.service
  notify:
  - restart respondd

- name: start respondd
  systemd:
    name: respondd.service
    state: started
    daemon_reload: yes
    enabled: yes
